name: GPy
channels:
  - defaults
dependencies:
  # install dependencies
  - python=3.7.4
  - pip
  - matplotlib
  - nose
  - pip:
    - paramz
    - codecov
    - coveralls
    - pypandoc
    - git+git://github.com/BRML/climin.git
    - autograd
    - nose-show-skipped
